spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: P@ssw0rd
  jpa:
    show-sql: false
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"