spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aluguel_maquinas
    username: root
    password: 
  jpa:
    show-sql: false
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"